
export const links = {
  qrimg: "/qrimgutil",
  state: "/state",
  type: "/typing",
  keyboard: "/keyboard?style=10",
  sessions: "/sessions?style=13",
  help: "/help",
  login: "/login",
  signin: "/login",
  logout: "/logout",
  signout: "/logout",
  register: "/signup",
  signup: "/signup",
  "auth.totp.enable": "/enable-totp",
  clock: "/1",
  "clock.zen": "/2",
  terminal: "/terminal?style=10",
  cmd: "/terminal?style=10",
  bash: "/terminal?style=10",
  shell: "/terminal?style=10",
  sh: "/terminal?style=10",
};
